datasheet/urls.py
from nturl2path import url2pathname
from django.urls import path, include
from django.views.generic import TemplateView
from datasheet import views
from datasheet.views import (CreateDataSheet, DeleteDataSheet, ListarFicha)

urlpatterns = [
    path('home/', views.Home, name='home'),
    path('view-datasheet/', views.ViewDataSheet, name='view_datasheet'),
    path('coordinacion-agua/<int:num>/', views.CoordinacionAgua, name='coordinacion_agua'),
    path('coordinacion-agua/nueva-acometida/<int:num>/', views.NuevaAcometida, name='nueva_acometida'),
    path('coordinacion-desechos-solidos/<int:num>/', views.CoordinacionDesechosSolidos, name='coordinacion_desechos_solidos'),
    path('coordinacion-alcantarillado/', views.CoordinacionAlcantarillado, name='coordinacion_alcantarillado'),
    path('create-datasheet/', CreateDataSheet.as_view(), name='create_datasheet'),
    path('edit-datasheet/<int:pk>/', views.EditDataSheet, name='edit_datasheet'),
    path('delete-datasheet/<int:pk>/',DeleteDataSheet.as_view(), name='delete_datasheet'),
    path('list-datasheet/', ListarFicha.as_view(), name='listar_fichas'),
    path('buscar/', views.buscarCampos, name='buscar_fichas'),
    path('start-datasheet/',TemplateView.as_view(
                                template_name='fichas.html'
                            ), name='inicio_fichas'),
]

registryapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from authentication.views import Login, logoutUsuario


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ficha/', include(('datasheet.urls', 'ficha'), namespace='ficha'), name='ficha'),
    path('accounts/login/', Login.as_view(), name = 'login'),
    path('logout/', login_required(logoutUsuario), name = 'logout'),
]

datasheet/views.py
import json
from itertools import chain
from email import header
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView,TemplateView
from django.core.serializers import serialize
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .static import constants
from .models import TbAbastecimientoAguaPotable, TbAccesorio, TbActividadPredio, TbAlmacenamientoAguaPotable, TbCaracteristicasConexion, TbDatosCajaAgua, TbDatosCajaRegistroDesague, TbDatosComplementarios, TbDatosConexionAguaPotable, TbDatosConexionAlcantarillado, TbDatosGeneralesUsuario, TbDatosInmueble, TbDatosMarcoTapaCajaAgua, TbDatosMedidor, TbDatosSinConexionAguaAlcantarillado, TbDatosTapaCajaAlcantarillado, TbDiametroConexion, TbDiametroConexionAlc, TbDiametroMedidor, TbEstadoCaja, TbEstadoCajaRD, TbEstadoMArcoTapa, TbEstadoTapa, TbFichaTecnica, TbJardinHuerto, TbMaterialCaja, TbMaterialCajaRD, TbMaterialConexion, TbMaterialConexionAlc, TbMaterialConstruccion, TbMaterialMarcoTapa, TbMaterialTapa, TbMedidorAccesorio, TbNuevoCodigoCatastral, TbPavimento, TbRecoleccionBasura, TbResponsablePredio, TbSaneamiento, TbSituacionConexion, TbSituacionConexionAlc, TbTipoPredio, TbTipoServicio, TbTipoUsuario, TbTipoVereda, TbUbicacionCajaRD, TbUbicacionCajagua, TbDatosResponsableAcometida
from .forms import TbDatosGeneralesUsuarioForm, TbNuevoCodigoCatastralForm, TbFichaTecnicaForm, TbDatosInmuebleForm, TbDatosConexionAguaPotableForm, TbDatosCajaAguaForm, TbDatosMarcoTapaCajaAguaForm, TbDatosMedidorForm, TbDatosConexionAlcantarilladoForm, TbDatosCajaRegistroDesagueForm, TbDatosTapaCajaAlcantarilladoForm, TbDatosSinConexionAguaAlcantarilladoForm, TbDatosComplementariosForm, TbRecoleccionBasuraForm

# Create your views here.
def Home(request):
  print(request.GET)
  return render(request, 'index.html')

def ViewDataSheet(request):
    tipo_usuarios= TbTipoUsuario.objects.all()
    predio_responsables= TbResponsablePredio.objects.all()
    tipo_predios = TbTipoPredio.objects.all()
    construccion_materiales = TbMaterialConstruccion.objects.all()
    servicio_tipos = TbTipoServicio.objects.all()
    predio_actividades = TbActividadPredio.objects.all()
    conexion_caracteristicas = TbCaracteristicasConexion.objects.all()
    conexion_diametros = TbDiametroConexion.objects.all()
    conexion_materiales = TbMaterialConexion.objects.all()
    conexion_situaciones = TbSituacionConexion.objects.all()
    caja_agua_ubicaciones = TbUbicacionCajagua.objects.all()
    caja_materiales = TbMaterialCaja.objects.all()
    caja_estados = TbEstadoCaja.objects.all()
    marco_tapa_materiales= TbMaterialMarcoTapa.objects.all()
    marco_tapa_estados= TbEstadoMArcoTapa.objects.all()
    medidor_diametros= TbDiametroMedidor.objects.all()
    accesorios= TbAccesorio.objects.all()
    alc_conexion_diametros= TbDiametroConexionAlc.objects.all()
    alc_conexion_materiales= TbMaterialConexionAlc.objects.all()
    alc_conexion_situaciones= TbSituacionConexionAlc.objects.all()
    caja_residual_ubicaciones= TbUbicacionCajaRD.objects.all()
    caja_residual_materiales= TbMaterialCajaRD.objects.all()
    caja_residual_estados= TbEstadoCajaRD.objects.all()
    tapa_materiales= TbMaterialTapa.objects.all()
    tapa_estados= TbEstadoTapa.objects.all()
    agua_potable_abastecimientos= TbAbastecimientoAguaPotable.objects.all()
    agua_potable_almacenamientos= TbAlmacenamientoAguaPotable.objects.all()
    saneamientos= TbSaneamiento.objects.all()
    jardin_huerto_tipos= TbJardinHuerto.objects.all()
    vereda_tipos= TbTipoVereda.objects.all()
    pavimentos= TbPavimento.objects.all()

    tb_nuevo_codigo_catastral= TbNuevoCodigoCatastral.objects.get(id=1)
    allData = TbFichaTecnica.objects.get(id=tb_nuevo_codigo_catastral.fichatecnica_id)
    datos_generales= TbDatosGeneralesUsuario.objects.get(id=allData.datos_generales_usuario_id)
    datos_inmueble= TbDatosInmueble.objects.get(id=allData.datos_inmueble_id)
    datos_agua_potable= TbDatosConexionAguaPotable.objects.get(id=tb_nuevo_codigo_catastral.datos_conexion_agua_potable_id)
    fecha_conexion_agua_potable= datos_agua_potable.fecha_instalacion.strftime("%Y-%m-%d") if datos_agua_potable.fecha_instalacion else ""
    datos_caja_agua= TbDatosCajaAgua.objects.get(id=tb_nuevo_codigo_catastral.datos_caja_agua_id)
    datos_marco_tapa_caja_agua= TbDatosMarcoTapaCajaAgua.objects.get(id=tb_nuevo_codigo_catastral.datos_marco_tapa_caja_agua_id)
    datos_medidor= TbDatosMedidor.objects.get(id=tb_nuevo_codigo_catastral.datos_medidor_id)
    medidor_accesorios= TbMedidorAccesorio.objects.filter(datos_medidor_id=tb_nuevo_codigo_catastral.datos_medidor_id)
    datos_conexion_alcantarillado= TbDatosConexionAlcantarillado.objects.get(id=allData.datos_conexion_alcantarillado_id)
    fecha_conexion_alcantarillado=  datos_conexion_alcantarillado.fecha_instalacion.strftime("%Y-%m-%d") if datos_conexion_alcantarillado.fecha_instalacion else ""
    datos_caja_registro_desague= TbDatosCajaRegistroDesague.objects.get(id=allData.datos_caja_registro_desague_id)
    datos_tapa_caja_alcantarillado= TbDatosTapaCajaAlcantarillado.objects.get(id=allData.datos_tapa_caja_alcantarillado_id)
    datos_sin_conexion_agua_alcantarillado= TbDatosSinConexionAguaAlcantarillado.objects.get(id=allData.datos_sin_conexion_agua_alc_id)
    datos_complementarios= TbDatosComplementarios.objects.get(id=allData.datos_complementarios_id)
    recoleccion_basura= TbRecoleccionBasura.objects.get(id=allData.recoleccion_basura_id)
    fecha_encuesta=  allData.fecha_encuesta.strftime("%Y-%m-%d") if allData.fecha_encuesta else ""

    context={
      'header': constants.title_ficha_catastral,
      'has_edit_permission': True,
      'edit_mode': False,

      'tipo_usuarios': tipo_usuarios,
      'predio_responsables': predio_responsables,
      'tipo_predios': tipo_predios,
      'construccion_materiales': construccion_materiales,
      'servicio_tipos': servicio_tipos,
      'predio_actividades': predio_actividades,
      'conexion_caracteristicas': conexion_caracteristicas,
      'conexion_diametros': conexion_diametros,
      'conexion_materiales': conexion_materiales,
      'conexion_situaciones': conexion_situaciones,
      'caja_agua_ubicaciones': caja_agua_ubicaciones,
      'caja_materiales': caja_materiales,
      'caja_estados': caja_estados,
      'marco_tapa_materiales': marco_tapa_materiales,
      'marco_tapa_estados': marco_tapa_estados,
      'medidor_diametros': medidor_diametros,
      'accesorios': accesorios,
      'alc_conexion_diametros': alc_conexion_diametros,
      'alc_conexion_materiales': alc_conexion_materiales,
      'alc_conexion_situaciones': alc_conexion_situaciones,
      'caja_residual_ubicaciones': caja_residual_ubicaciones,
      'caja_residual_materiales': caja_residual_materiales,
      'caja_residual_estados': caja_residual_estados,
      'tapa_materiales': tapa_materiales,
      'tapa_estados': tapa_estados,
      'agua_potable_abastecimientos': agua_potable_abastecimientos,
      'agua_potable_almacenamientos': agua_potable_almacenamientos,
      'saneamientos': saneamientos,
      'jardin_huerto_tipos': jardin_huerto_tipos,
      'vereda_tipos': vereda_tipos,
      'pavimentos': pavimentos,

      # 'data':allData,
      # 'nuevo_cod_catastral': nuevo_cod_catastral,
      # 'datos_generales': datos_generales,
      # 'datos_inmueble': datos_inmueble,
      # 'datos_agua_potable': datos_agua_potable,
      # 'fecha_conexion_agua_potable': fecha_conexion_agua_potable,
      # 'datos_caja_agua': datos_caja_agua,
      # 'datos_marco_tapa_caja_agua': datos_marco_tapa_caja_agua,
      # 'datos_medidor': datos_medidor,
      # 'medidor_accesorio': medidor_accesorio,
      # 'datos_conexion_alcantarillado': datos_conexion_alcantarillado,
      # 'fecha_conexion_alcantarillado': fecha_conexion_alcantarillado,
      # 'datos_caja_registro_desague': datos_caja_registro_desague,
      # 'datos_tapa_caja_alcantarillado': datos_tapa_caja_alcantarillado,
      # 'datos_sin_conexion_agua_alcantarillado': datos_sin_conexion_agua_alcantarillado,
      # 'datos_complementarios': datos_complementarios,
      # 'recoleccion_basura': recoleccion_basura,
      # 'fecha_encuesta': fecha_encuesta,
    }
    return render(request, 'view_datasheet.html', context)


def CoordinacionAgua(request, num):
  if request.method == 'GET': 
    tipo_usuarios= TbTipoUsuario.objects.all()
    predio_responsables= TbResponsablePredio.objects.all()
    tipo_predios = TbTipoPredio.objects.all()
    construccion_materiales = TbMaterialConstruccion.objects.all()
    servicio_tipos = TbTipoServicio.objects.all()
    predio_actividades = TbActividadPredio.objects.all()
    conexion_caracteristicas = TbCaracteristicasConexion.objects.all()
    conexion_diametros = TbDiametroConexion.objects.all()
    conexion_materiales = TbMaterialConexion.objects.all()
    conexion_situaciones = TbSituacionConexion.objects.all()
    caja_agua_ubicaciones = TbUbicacionCajagua.objects.all()
    caja_materiales = TbMaterialCaja.objects.all()
    caja_estados = TbEstadoCaja.objects.all()
    marco_tapa_materiales= TbMaterialMarcoTapa.objects.all()
    marco_tapa_estados= TbEstadoMArcoTapa.objects.all()
    medidor_diametros= TbDiametroMedidor.objects.all()
    accesorios= TbAccesorio.objects.all()
    jardin_huerto_tipos= TbJardinHuerto.objects.all()
    vereda_tipos= TbTipoVereda.objects.all()
    pavimentos= TbPavimento.objects.all()


    tb_nuevo_codigo_catastral= TbNuevoCodigoCatastral.objects.get(id=num)

    tb_ficha_tecnica = TbFichaTecnica.objects.get(id=tb_nuevo_codigo_catastral.fichatecnica_id)
    datos_responsableacometida= TbDatosResponsableAcometida.objects.get(id=tb_nuevo_codigo_catastral.responsableacometida_id)

datasheet/templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <!-- nuevo -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Catastro</title>
    <meta name="description" content="Catastro">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{% static 'images/logo.png' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block extra_css %}
    {% endblock extra_css %}
    <title>Catastro</title>
  </head>
  <body>
    {% include 'lateral_navbar.html' %}
    <div id="right-panel" class="right-panel">
      {% include 'navbar.html' %}
      <div class="content">
        {% block content %}

        {% endblock %}
      </div>

      <div class="clearfix"></div>
      <!-- Footer -->
      <footer class="site-footer">
          <div class="footer-inner bg-white">
              <div class="row">
                  <div class="col-sm-6">
                      Copyright &copy; 2022
                  </div>
                  <div class="col-sm-6 text-right">
                      Designed by <a href=""></a>
                  </div>
              </div>
          </div>
      </footer>
      <!-- /.site-footer -->
    </div>
      
    <!-- Scripts -->
    <script>
      (function() {
        var $sidebar   = $("#sideBar-expanded"), 
            $window    = $(window),
            offset     = $sidebar.offset(),
            topPadding = 15;

        $window.scroll(function() {
          console.log("scroll");
            if ($window.scrollTop() > offset.top) {
                $sidebar.stop().animate({
                    marginTop: $window.scrollTop() - offset.top + topPadding
                });
            } else {
                $sidebar.stop().animate({
                    marginTop: 0
                });
            }
        });
      });
    </script>
    <script>
      function closeNav() {
        var side_navbar_expanded = document.getElementById("sideBar-expanded");
        var side_navbar_reduce = document.getElementById("sideBar-reduce");
        if(side_navbar_expanded.style.display === '' || side_navbar_expanded.style.display === 'block'){
          side_navbar_expanded.style.display = "none";
          side_navbar_reduce.style.display = "block";
          return;
        }
        side_navbar_expanded.style.display = "block";
        side_navbar_reduce.style.display = "none";
      }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
      {% for m in messages %}
        <script>
          Swal.fire({
            "title": "¡Correcto!",
            "text": "{{m}}",
            "icon": "success"
          })
        </script>
      {% endfor %}
    {% endif %}
    {% block extrajs %}
    {% endblock extrajs %}
  </body>
</html>

datasheet/templates/buscar.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}" />
<form action="/ficha/buscar/"  method="POST">
    {% csrf_token %}
    {% include 'general_elements/search_bar.html' %}
    {% include 'listar_generaldatos_ficha.html' %}
</form>
{% endblock %}

datasheet/templates/fichas.html
{% extends 'base.html' %} 
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/lib/datatable/dataTables.bootstrap.min.css' %}">
{% endblock extra_css %}
{% block content %}
<div class="clearfix"></div>
<div class="orders">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title ">LISTADO DE FICHAS</h4>
                    <div class="col-md-4 mt-3">
                        <!-- <button type="button" class="btn btn-success" onclick="abrir_modal_creacion('{% url 'ficha:create_datasheet' %}');">
                            CREAR FICHA 
                        </button> -->
                        <a class="btn btn-success" href="{% url 'ficha:create_datasheet' %}">CREAR FICHA</a>
                    </div>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table id="tabla_fichas" class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>NÚMERO FICHA</th>
                                    <th>CÉDULA DE IDENTIDAD</th>
                                    <th>CÓDIGO CATASTRAL ACTUAL</th>
                                    <th>NUEVO CÓDIGO CATASTRAL</th>
                                    <th>FECHA</th>
                                    <th>OBSERVACIONES</th>
                                    <th>ACCIONES</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div> 
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">

</div>

{% endblock %}
{% block extrajs %}
    <script src="{% static 'js/lib/data-table/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/lib/data-table/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/ficha/ficha.js' %}"></script>
{% endblock extrajs %}

datasheet/templates/index.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}
<div class="row justify-content-center align-items-center" style="height: 600px; background-color: white">
    <div class="col-lg-12">
        <div class="card bg-success me-5 mx-5">
            <div class="card-body">
                <blockquote class="blockquote mb-0 text-light text-center">
                    <h1 class="text-light">¡{{ user.username | upper }} BIENVENIDO!</h1>
                </blockquote>
            </div>
        </div>
    </div>
</div>
{% endblock %}

datasheet/templates/lateral_navbar.html
{% load static %} 
<!-- Left Panel -->
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'ficha:home' %}"><i class="menu-icon fa fa-home"></i>Inicio</a>
                </li>
                <li class="menu-title">OPCIONES</li><!-- /.menu-title -->
                <li class="">
                    <a href="{% url 'ficha:inicio_fichas' %}"><i class="menu-icon fa fa-file-text-o"></i>Fichas</a>
                </li>
                <!-- <li class="menu-item-has-children dropdown">
                    <a href="{% url 'ficha:inicio_fichas' %}" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file-text-o"></i>Fichas</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-square-o"></i><a href="{% url 'ficha:create_datasheet' %}">Crear Fichas</a></li>
                    </ul>
                </li> -->
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bars"></i>Usuarios</a>
                    <ul class="sub-menu children dropdown-menu">                            
                        <li><i class="fa fa-puzzle-piece"></i><a href="ui-buttons.html">Buttons</a></li>
                        <li><i class="fa fa-id-badge"></i><a href="ui-badges.html">Badges</a></li>
                        <li><i class="fa fa-bars"></i><a href="ui-tabs.html">Tabs</a></li>
                        <li><i class="fa fa-id-card-o"></i><a href="ui-cards.html">Cards</a></li>
                        <li><i class="fa fa-exclamation-triangle"></i><a href="ui-alerts.html">Alerts</a></li>
                        <li><i class="fa fa-spinner"></i><a href="ui-progressbar.html">Progress Bars</a></li>
                        <li><i class="fa fa-fire"></i><a href="ui-modals.html">Modals</a></li>
                        <li><i class="fa fa-book"></i><a href="ui-switches.html">Switches</a></li>
                        <li><i class="fa fa-th"></i><a href="ui-grids.html">Grids</a></li>
                        <li><i class="fa fa-file-word-o"></i><a href="ui-typgraphy.html">Typography</a></li>
                    </ul>
                </li>   
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside>
<!-- /#left-panel -->

datasheet/templates/navbar.html
{% load static %}
<!-- Header-->
<header id="header" class="header">
    <div class="top-left">
        <div class="navbar-header">
            <a class="navbar-brand" href="./"><img src="{% static 'images/logo.png' %}" alt="Logo"></a>
            <a class="navbar-brand hidden" href="./"><img src="{% static 'images/logo.png' %}" alt="Logo"></a>
            <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
    </div>
    <div class="top-right">
        <div class="header-menu">
            <div class="header-left">
                <button class="search-trigger"><i class="fa fa-search"></i></button>
                {{ user.username | upper }}
                <div class="form-inline">
                    <form class="search-form" action="{% url 'ficha:listar_fichas'  %}" method="GET">
                        <input class="form-control mr-sm-2" type="text" name="buscar" placeholder="Buscar ..." aria-label="Search">
                        <button  type="submit">Buscar </button>
                        <i class="fa fa-close"></i>
                    </form>
                </div>
            </div>

            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="{% static 'images/admin.jpg' %}" alt="User Avatar">
                </a>

                <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="#"><i class="fa fa-user"></i>Mi perfil</a>

                    <a class="nav-link" href="#"><i class="fa fa-cog"></i>Configuraciones</a>

                    <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-power-off"></i>Cerrar Sesión</a>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- /#header -->

datasheet/templates/tbfichatecnica_confirm_delete.html
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Ésta acción no se puede deshacer</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body text-center">{% csrf_token %}
        <h2><strong>¿Está seguro que desea eliminar la Ficha Nro. {{ object }} ?</strong></h2>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">CANCELAR</button>
        <button type="button" class="btn btn-danger" data-align="right"
                onclick="eliminarFicha({{ object.pk }});"><strong>CONFIRMAR ELIMINACIÓN</strong></button>
    </div>
    </div>
</div>